### ISSUE TITLE
Please provide aarch64 build

### ISSUE THREAD

**Issue by Karry** [almindor/lighthouse#27]
Hi. 

Jolla released full SFOS for Xperia 10.II yesterday. On this device just aarch64 applications may be used. It would be great to provide aarch64 build of Lighthouse in store/openrepos.

**Comment by almindor** [comment]
Right now the latest sailfish SDK doesn't work for me so I can't do anything. I don't have time to debug Jolla issues atm, too busy with other stuff. Feel free to fork and build if needed.

**Comment by Karry** [comment]
Well, I can share my build (if you trust me :-) ), current master with recent virtualbox SDK works for me. You are just busy right now, or you don't want to maintain this app anymore? 

my build script:
```
#!/bin/bash

set -xe
PATH=$PATH:~/SailfishOS/bin/

export OS_VERSION=4.0.1.48
export ARCHITECTURE=aarch64
export DEV_DEVICE=Xperia

sfdk config "no-fix-version"
sfdk config "target=SailfishOS-${OS_VERSION}-${ARCHITECTURE}"
sfdk build --enable-debug

sfdk config "device=${DEV_DEVICE}"
if [ $? -ne 0 ] ; then
  echo
  echo "Available devices:"
  sfdk device list 2> /dev/null
  exit 1;
fi

sfdk deploy --sdk
```

[RPMS.zip](https://github.com/almindor/lighthouse/files/6564997/RPMS.zip)

**Comment by almindor** [comment]
I'm both busy but also have been somewhat disillusioned with the quality of
the SDK the last 2 years or so. I've only had more and more trouble from
broken debugging all the way down to unusable build system due to bugs or
library compatibility issues.

I'll try to set things up again and see if it works without too much hustle.

so 29. 5. 2021 o 9:35 Lukáš Karas ***@***.***> napísal(a):

**Comment by rinigus** [comment]
Build is available at Chum now
